// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdtogvrdutvblznpzyjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdG9ndnJkdXR2Ymx6bnB6eWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODQ0NzUsImV4cCI6MjA2MTk2MDQ3NX0.uyHeeFRPA4UYXFmudWaHSsM5Rtdz7sR4YFKljO3tOYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);